spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      max-lifetime: 18000
      connection-timeout: 30000
  jackson:
    serialization:
      indent-output: true
    time-zone: GMT+8
  jpa:
    show-sql: false
    open-in-view: false
