@baseUrl = http://localhost:8080

###############################################
# PermissionController 相关接口 (需要认证)
###############################################

### 获取权限树
GET {{baseUrl}}/permissions/tree
Authorization: Bearer {{token}}
Accept: application/json

### 权限分页查询
GET {{baseUrl}}/permissions/page?page=0&size=10
Authorization: Bearer {{token}}
Accept: application/json

### 权限分页查询 - 按名称搜索
GET {{baseUrl}}/permissions/page?page=0&size=10&search_AND_EQ_name=用户
Authorization: Bearer {{token}}
Accept: application/json


### 根据ID查询权限详情
GET {{baseUrl}}/permissions/findById/6926c81d8f79d5db9a7e3103
Authorization: Bearer {{token}}
Accept: application/json

### 保存权限
POST {{baseUrl}}/permissions/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "parentId": "6926c81d8f79d5db9a7e3103",
  "name": "用户管理",
  "val": "/system/user/**",
  "identification": "system",
  "icon": "el-icon-setting",
  "jumpPath": "/system",
  "type": "catalogue",
  "orderNum": 1,
  "remark": "系统管理目录"
}


### 更新权限
POST {{baseUrl}}/permissions/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "6927b3e0fef931981b72ff9b",
  "parentId": "6926c81d8f79d5db9a7e3103",
  "name": "用户管理",
  "val": "/system/user",
  "identification": "system:user",
  "icon": "el-icon-user-solid",
  "jumpPath": "/system/user/list",
  "type": "menu",
  "orderNum": 1,
  "remark": "用户管理菜单 - 已更新"
}

### 删除权限
DELETE {{baseUrl}}/permissions/delete
Authorization: Bearer {{token}}
Content-Type: application/json

["6927b3e0fef931981b72ff9b"]

