@baseUrl = http://localhost:8080

###############################################
# RoleController 相关接口 (需要认证)
###############################################

### 角色分页查询
GET {{baseUrl}}/role/page?page=0&size=10
Authorization: Bearer {{token}}
Accept: application/json

### 角色分页查询 - 按名称搜索
GET {{baseUrl}}/role/page?page=0&size=10&search_AND_EQ_name=管理员
Authorization: Bearer {{token}}
Accept: application/json


### 根据ID查询角色详情
GET {{baseUrl}}/role/findById/6926c5bb8f79996afe1104cc
Authorization: Bearer {{token}}
Accept: application/json

### 保存新角色
POST {{baseUrl}}/role/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "系统管理员"
}

### 更新角色信息
POST {{baseUrl}}/role/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "6926c5bb8f79996afe1104cc",
  "name": "超级管理员"
}


### 删除角色
DELETE {{baseUrl}}/role/delete
Authorization: Bearer {{token}}
Content-Type: application/json

["6927b329fef931981b72ff99"]


### 为角色设置权限
POST {{baseUrl}}/role/givePermission/6927b329fef931981b72ff99
Authorization: Bearer {{token}}
Content-Type: application/json

["6927b3e0fef931981b72ff9b"]


